/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataBase.MenuFactory;
import DataBase.MenuInterface;
import DataStructures.Trie;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import foodcourt.FoodCourtModel;
import foodcourt.Menu_Items;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.List;
import java.awt.Toolkit;
import java.awt.print.PrinterJob;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import javax.print.Doc;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.Sides;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.printing.PDFPageable;


/**
 *
 * @author u20o90
 */
public class NewOrder extends javax.swing.JFrame {

    /**
     * Creates new form NewOrder
     */
    ArrayList<Menu_Items> items;
    Trie trie;
    FoodCourtModel foodcourt;
    MainScreen mainscreen;
    public NewOrder(FoodCourtModel foodcourt,MainScreen mainscreen) {
        initComponents();
        setExtendedState(this.MAXIMIZED_BOTH); 
       
         
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);
         
        trie = new Trie();
        this.foodcourt = foodcourt;
        this.mainscreen = mainscreen;
       

        GetItems();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        SeachItem = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        list1 = new java.awt.List();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BillingTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(580, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Please Place Your Order");
        jPanel1.add(jLabel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 375));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Top Picks");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addGap(35, 35, 35)
                .addComponent(jButton2)
                .addGap(33, 33, 33)
                .addComponent(jButton3)
                .addGap(32, 32, 32)
                .addComponent(jButton4)
                .addGap(32, 32, 32)
                .addComponent(jButton5)
                .addContainerGap(749, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Search");

        SeachItem.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        SeachItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SeachItemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(SeachItem, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeachItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel8);

        jPanel10.setBackground(new java.awt.Color(255, 51, 51));
        jPanel10.setPreferredSize(new java.awt.Dimension(549, 300));

        list1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        list1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel10);

        jPanel9.setPreferredSize(new java.awt.Dimension(549, 600));

        BillingTable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BillingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "QTY", "Price"
            }
        ));
        BillingTable.setRowHeight(25);
        BillingTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BillingTableFocusLost(evt);
            }
        });
        BillingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BillingTableMouseClicked(evt);
            }
        });
        BillingTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BillingTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(BillingTable);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cancel.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clear.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/checkout.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanel9);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeachItemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SeachItemKeyReleased
        // TODO add your handling code here:Key relaes
                list1.removeAll();
                String enteredstring =  SeachItem.getText().trim();
                for (Menu_Items item : this.items) {
                if(item.getName().toLowerCase().startsWith(enteredstring.toLowerCase()))
                {
                    list1.add(item.getName());
                }
        }
                
        
    }//GEN-LAST:event_SeachItemKeyReleased

    private void list1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list1MouseClicked
        // TODO add your handling code here:
        SeachItem.setText("");
        for(Menu_Items item : items)
        {
            if(item.getName().toLowerCase().equalsIgnoreCase(list1.getSelectedItem().toLowerCase()))
            {
                DefaultTableModel  model = (DefaultTableModel) BillingTable.getModel();
                Object row[] = new Object[3];
      
                row[0] = item.getName();
                row[1] = "1";
                row[2] = item.getPrice();
                model.addRow(row);
       
                list1.removeAll();
                break;
            }
            
        }
    }//GEN-LAST:event_list1MouseClicked
    //code for bill makinng
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
                 DefaultTableModel  model = (DefaultTableModel) BillingTable.getModel();
                 int rows = model.getRowCount();
                 float Total = 0;
                 
            for(int i = 0 ; i < rows ;  i ++)
            {
                        
            Total = Total + Float.valueOf(""+ model.getValueAt(i, 2));
      
                
            }
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Checkout Total amount  "+Total, "Bill Confirmation", dialogButton);
        if(dialogResult == 0) {
          System.out.println("Yes option");
        } else {
          System.out.println("No Option");
          return;
        } 
         Total = 0 ;
        Document doc = new Document();
        try{
            PdfWriter writer = PdfWriter.getInstance(doc, new FileOutputStream("C:/Foodcourt/text.pdf"));

            doc.open();
             doc.add(new Paragraph("Powered By Stark Technology"));
            
            Image img = Image.getInstance("StarkLogo.jpg");
            doc.add(img);
            
            doc.add(new Paragraph("welcome to "+foodcourt.getName(),FontFactory.getFont(FontFactory.TIMES_BOLD,30,Font.BOLD,BaseColor.BLACK)));
            doc.add(new Paragraph(new Date().toString()));
            doc.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
            
            doc.add(new Paragraph("Your Order Details",FontFactory.getFont(FontFactory.TIMES_BOLD,15,Font.BOLD,BaseColor.BLACK)));
            
            PdfPTable table = new PdfPTable(4);
            table.setWidthPercentage(105);
            table.setSpacingBefore(11f);
            table.setSpacingAfter(11f);
            
            float[] colwidth = {2f,2f,2f,2f};
            table.setWidths(colwidth);
            
            PdfPCell c1 = new PdfPCell(new Paragraph("Sno"));   
            PdfPCell c2 = new PdfPCell(new Paragraph("Item Name"));
            PdfPCell c44= new PdfPCell(new Paragraph("QTY"));   
            PdfPCell c3  = new PdfPCell(new Paragraph("Price"));  
            table.addCell(c1);
            table.addCell(c2);
            table.addCell(c44);
            table.addCell(c3);
            
            for(int i = 0 ; i < rows ;  i ++)
            {
                        
            c1 = new PdfPCell(new Paragraph(""+(i+1)));   
           
            c2 = new PdfPCell(new Paragraph(""+ model.getValueAt(i, 0)));
            c44= new PdfPCell(new Paragraph(""+ model.getValueAt(i, 1)));
            c3  = new PdfPCell(new Paragraph(""+ model.getValueAt(i, 2)));
            Total = Total + Float.valueOf(""+ model.getValueAt(i, 2));
            table.addCell(c1);
            table.addCell(c2);
            table.addCell(c44);
            table.addCell(c3);
                
            }
            
            
            doc.add(table);
            
            PdfPTable table2= new PdfPTable(2);
            table2.setWidthPercentage(105);
  
            
            float[] colwidth2 = {1f,1f};
            table2.setWidths(colwidth2);
            
            PdfPCell c4 = new PdfPCell(new Paragraph("Total  "));  
         
            c4.setBorder(PdfPCell.NO_BORDER);
            PdfPCell c5 = new PdfPCell(new Paragraph("Rs :-   "+Total));   
            c5.setBorder(PdfPCell.NO_BORDER);
               
            PdfPCell c6 = new PdfPCell(new Paragraph("CGST : "+foodcourt.getCGST()+" %"));  
            c6.setBorder(PdfPCell.NO_BORDER);
            PdfPCell c7 = new PdfPCell(new Paragraph("Rs :-   0"));   
            c7.setBorder(PdfPCell.NO_BORDER);   
     
            
            PdfPCell c8 = new PdfPCell(new Paragraph("SGST : "+foodcourt.getGGST()+" %"));  
            c8.setBorder(PdfPCell.NO_BORDER);
            PdfPCell c9 = new PdfPCell(new Paragraph("Rs :-   0"));   
            c9.setBorder(PdfPCell.NO_BORDER);  
            
            
            PdfPCell c10 = new PdfPCell(new Paragraph("Grand Total "));  
            c10.setBorder(PdfPCell.NO_BORDER);
            PdfPCell c11 = new PdfPCell(new Paragraph("Rs :-   "+Total));   
            c11.setBorder(PdfPCell.NO_BORDER);  
            
            
            table2.addCell(c4);
            table2.addCell(c5);
            table2.addCell(c6);
            table2.addCell(c7);
            table2.addCell(c8);
            table2.addCell(c9);
            table2.addCell(c10);
            table2.addCell(c11);
            
            
            
            doc.add(table2);
            
            doc.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
            doc.add(new Paragraph("Thanx for your Visit have a nice day , enjoy your meal."));
            doc.add(new Paragraph("Contact us",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD,BaseColor.BLACK)));
            doc.add(new Paragraph("Address : gurugram"));
            doc.add(new Paragraph("Phone : 9718327876"));
            
  
            
            doc.close();
            writer.close();
     

            DocFlavor flavor = DocFlavor.SERVICE_FORMATTED.PAGEABLE;
            PrintRequestAttributeSet patts = new HashPrintRequestAttributeSet();
            patts.add(Sides.DUPLEX);
            PrintService[] ps = PrintServiceLookup.lookupPrintServices(flavor, patts);
            if (ps.length == 0) {
            throw new IllegalStateException("No Printer found");
            }
            System.out.println("Available printers: " + Arrays.asList(ps));

            PrintService myService = null;
            
            for (PrintService printService : ps) 
            {
               
                      try{
                             myService = printService;
                             FileInputStream fis = new FileInputStream("C:/Foodcourt/text.pdf");
                             Doc pdfDoc = new SimpleDoc(fis, DocFlavor.INPUT_STREAM.AUTOSENSE, null);
                             DocPrintJob printJob = myService.createPrintJob();
                             printJob.print(pdfDoc, new HashPrintRequestAttributeSet());
                             fis.close();   
                             break;
                      }catch(Exception e)
                      {
                          System.out.println("  HERE  ");
                      }
            
            }

       

     
        }catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void BillingTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BillingTableKeyReleased
        // TODO add your handling code here:
            DefaultTableModel  model = (DefaultTableModel) BillingTable.getModel();
            int rows = model.getRowCount();
        
                 
            for(int i = 0 ; i < rows ;  i ++)
            {
                        
            int qty = Integer.valueOf(""+ model.getValueAt(i, 1));
            if(qty != 1)
            {
                float value=0;
               for(Menu_Items item : items)
                {
                 if(item.getName().toLowerCase().equalsIgnoreCase(model.getValueAt(i, 0).toString().toLowerCase()))
                {
               
                  value = qty * Float.valueOf(item.getPrice());
                  break;
                  }
            
                  }
                model.setValueAt(value, i, 2);
            }
      
                
            }
        
    }//GEN-LAST:event_BillingTableKeyReleased

    private void BillingTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BillingTableFocusLost
        // TODO add your handling code here:
            DefaultTableModel  model = (DefaultTableModel) BillingTable.getModel();
            int rows = model.getRowCount();
        
                 
            for(int i = 0 ; i < rows ;  i ++)
            {
                        
            int qty = Integer.valueOf(""+ model.getValueAt(i, 1));
            if(qty != 1)
            {
                float value=0;
               for(Menu_Items item : items)
                {
                 if(item.getName().toLowerCase().equalsIgnoreCase(model.getValueAt(i, 0).toString().toLowerCase()))
                {
               
                  value = qty * Float.valueOf(item.getPrice());
                  break;
                  }
            
                  }
                model.setValueAt(value, i, 2);
            }
      
                
            }
        
    }//GEN-LAST:event_BillingTableFocusLost

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    
         
            DefaultTableModel dm = (DefaultTableModel) BillingTable.getModel();
            int rowCount = dm.getRowCount();
            //Remove rows one by one from the end of the table
            for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void BillingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillingTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BillingTableMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        mainscreen.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BillingTable;
    private javax.swing.JTextField SeachItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables

   private void GetItems() 
    {
        
        MenuInterface Dao = MenuFactory.GetInstance();
        try
        {
            this.items = Dao.GetItems("Demo",trie);
        }
        catch (Exception ex) 
        {
            System.out.println("Failed loading items"+ex);
            return;
        }
        
        
    }
private static PrintService findPrintService(String printerName) {
        PrintService[] printServices = PrintServiceLookup.lookupPrintServices(null, null);
        for (PrintService printService : printServices) {
            if (printService.getName().trim().equals(printerName)) {
                return printService;
            }
        }
        return null;
    }

}
