/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author dimri
 */
public class recharge extends javax.swing.JDialog {

    /**
     * Creates new form recharge
     */
    public recharge(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
                                   Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
    int x = (int) ((dimension.getWidth() - getWidth()) / 2);
    int y = (int) ((dimension.getHeight() - getHeight()) / 2);
    setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 610));
        setMinimumSize(new java.awt.Dimension(1000, 610));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Amount");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 130, 240, 60);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Clear.png"))); // NOI18N
        jButton1.setText("Clear");
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 340, 180, 137);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cardrecharge.png"))); // NOI18N
        jButton2.setText("Recharge");
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 340, 150, 70);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cardrefund.png"))); // NOI18N
        jButton3.setText("Refund");
        getContentPane().add(jButton3);
        jButton3.setBounds(680, 340, 170, 70);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(510, 130, 290, 80);

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton3.setText("500");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(530, 270, 100, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Existing Amount");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 460, 320, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Card No");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 40, 240, 60);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(510, 40, 290, 80);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(540, 460, 290, 80);

        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton5.setText("1000");
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(730, 270, 100, 40);

        jRadioButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton6.setText("200");
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(380, 270, 100, 40);

        jRadioButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton7.setText("100");
        getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(220, 270, 100, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 450, 1080, 2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
